# =====================================================
# Title:         Main Sy=ummary Table
# Description:   
# Author:        Chi-Chao Hung
# Version:       v1.0

# Change Log:
# - 2025-02-04

# Inputs:        
# Outputs:       
# Replication:   [Instructions for reproducing the results, e.g., "Run scripts in the following order..."]
# Notes:         [Additional notes about assumptions, data sources, or ethical considerations]
# =====================================================

# --- 1. Initialize Environment --------
# Load required libraries
library(data.table)
require(kableExtra)
# Set random seed for reproducibility
set.seed(1234)

# --- 2. Set Working Directory ------
# Specify file paths for data, output, and script storage
setwd("/Users/hungchichao/Documents/GitHub/College_Department_Choice")

# --- 3. Load Data ---------------
enrolled_dt <- fread("01data/enrolled_data250107.csv")
# id, gender_full_name, exam_erea, location, Year

choice_set_long <- fread("01Data/Choice_set_long0107.csv")
# y_id ids Gender, exam_area, year City Town region 
# make sure every obs has corresponding characteristics
choice_set_long <- choice_set_long[field != "" & alt_school != "", ]

# --- 4. Generate summary statistics and plots ---------

# Enrolled
enrolled_idv <- enrolled_dt[, .(.N, Admitted = sum(status %in% c("正","正取"))) , 
                            by = .(Year, id, Gender_full_name, exam_area, location,
                                   school_0, department_0, status_0, rank_0)]

# Reveal Preference
sample1 <- copy(choice_set_long)
sample1 <- sample1[, .( .N ), by = .(year, ids, Gender, exam_area, location, school, Ch, 
                                     g1, g2, g3, choice, c_wage) ]


# GSAT Score
choice_set_long2 <- choice_set_long2[ ! is.na(Ch)]

# With Wage and Distance
sample2 <- choice_set_long2[ ! is.na(c_wage) & ! is.na(alt_wage) 
                             & ! is.na(UX) & !is.na(SX)] # Wage and distance
sample2 <- sample2[, .( .N ), by = .(year, ids, Gender, exam_area, location, school, Ch,
                                     g1, g2, g3, choice, c_wage) ]


# Define a function that can run multiple times
summary_table <- function(dt) {
  city <- c("台北","台中","台南","高雄","桃園","新北")
  
  total_obs <- dt[, .N]  # 總樣本數
  city_obs <- dt[location %in% city, .N]  # 目標城市的樣本數
  total_sd <- dt[, uniqueN(choice)]
  
  dt1 <- data.table(
    Var = c("Female","Male","Neutral","Unidentified","City (%)", "Obs", "Size",
            "GSAT","Program Num.", "School Num.","W/ earning"),
    Value = c(
      dt[, round((.N/total_obs)*100, 2) , by = Gender]$V1, # Gender
      round((city_obs / total_obs) * 100, 2),              # 計算百分比
      as.character(total_obs),                             # Obs.
      round(dt[, .(mean_count = mean(N))]$mean_count, 2),   #Set Size
      round( (dt[ ! is.na(Ch), .N ]/total_obs)*100 , 2),
      as.character(total_sd),
      dt[, uniqueN(school)],
      dt[ ! is.na(c_wage) , round( (uniqueN(choice)/total_sd)*100.2) ]
    )
  )
}
# 計算兩個 data.table 的 summary
row2.1 <- summary_table(sample1)
row2.2 <- summary_table(sample2)
# 合併表格
row2 <- merge(row2.1, row2.2, by = "Var", suffixes = c("_dt1", "_dt2"), sort = FALSE)

latex = TRUE
# 輸出
kb <- kbl(row2, format = if(latex == T){"latex"}, 
            caption = "Summary Statistics", 
            booktabs = T) %>% 
    kable_styling() %>%
    #add_header_above(c(" "= 1, "Sample I" = 2, "Sample II" = 2 ))%>%
    pack_rows("Gender", 1, 4, italic = T) %>%
    #pack_rows("Exam Area", 7, 9, italic = T) %>%
    footnote(number = c("Footnote 1; "),
             general = "This is generated by kableExtra",
             threeparttable = T)

filename <- paste0("Sum_stats",format(Sys.Date(), "%m%d") ,".tex")
writeLines(kb, con = filename)

